# Generated by Django 3.2.3 on 2021-06-16 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=80)),
                ('path', models.CharField(max_length=80)),
                ('timestamp', models.DateField()),
            ],
        ),
    ]
